spring.application.name=grandflow
server.port=10000
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:12345/grandflowdb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:accounting}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jackson.time-zone=Asia/Jakarta
spring.thymeleaf.cache=false
app.theme.name=grandflow
app.theme.footer-text=GrandFlow
springdoc.packages-to-scan=com.grandindo.grandflow.controller.api
